import { useEffect, useMemo, useRef, useState } from 'react';
import QRCode from 'qrcode';
import { ArrowDown, ArrowRight, ArrowUpRight, Mail, MapPin, Menu, Phone, X } from 'lucide-react';
import { NetworkCanvas } from '@/lib/NetworkCanvas';
import { useMouse, useReducedMotion, useScrolled, useScrollProgress } from '@/lib/scroll';

const candidateImage = '/images/CS_manish_website.png';
const siteUrl = 'https://csmanishkumar.com';
const contact = { email: 'consult@csmanishkumar.com', phone: '6291109642', phoneIntl: '+916291109642', location: 'Kolkata' };
const commitments = [
{number:'01',title:'Professional Development & Practice Excellence',label:'For All Members — Measurable, Inclusive',copy:'Create opportunities for continuous professional development, practical learning and excellence in practice — with measurable and inclusive growth for members across different stages of their careers.'},
{number:'02',title:'Student Success & Career Readiness',label:'In All Domains',copy:'Strengthen student development and career readiness across diverse domains, helping students build practical skills, confidence and clearer pathways into professional opportunities.'},
{number:'03',title:'Employment & Training Opportunities',label:'Driving Unemployment Toward Zero & Ending Training Stagnancy',copy:'Work toward expanding employment, training and practical exposure while addressing training stagnancy and creating stronger bridges between talent and opportunity.'},
{number:'04',title:'Communication & Leadership Development',label:'Making Global Leaders',copy:'Develop communication, leadership and professional confidence so students and members can represent themselves effectively and grow into globally capable professionals.'},
{number:'05',title:'Inculcating Digital & AI Capabilities',label:'Amongst Students & Members',copy:'Promote practical digital and AI capabilities among students and members so the profession remains relevant, competitive and ready for a rapidly changing business environment.'},
{number:'06',title:'Grassroots Development & Institutional Collaborations',label:'Throughout the Region',copy:'Strengthen grassroots development and build meaningful collaborations with educational institutions, professional bodies and other relevant stakeholders throughout the region.'},
{number:'07',title:'Visible Member Engagement & Recognition',label:'Including Community Development',copy:'Create more opportunities for members to participate, contribute and be recognized — including initiatives connected with community development and professional engagement.'},
{number:'08',title:'Welfare Through Corporate, Industrial & Government Liaison & Representation',label:'Stronger Representation. Better Connections.',copy:'Strengthen constructive liaison and representation with corporate, industrial and government stakeholders to support member welfare and create meaningful professional opportunities.'},
{number:'09',title:'Organized Research & Information Repository',label:'For Greater Knowledge & Skill Development',copy:'Develop organized research and information resources that help students and members access knowledge, develop skills and make better-informed professional decisions.'},
{number:'10',title:'Accessible, Transparent & Stakeholder-Centric EIRC',label:'An EIRC That Listens, Connects & Responds',copy:'Work toward an accessible, transparent and stakeholder-centric EIRC where students, members and other stakeholders can engage more effectively with the institution.'}
];
const pages: Record<string,{title:string;description:string}>={
'/':{title:'CS Arisankala Manish Kumar | Company Secretary & Professional Vision',description:'Explore the professional vision and commitments of CS Arisankala Manish Kumar — focused on opportunity, capability, leadership and stronger institutions.'},
'/about':{title:'About | CS Arisankala Manish Kumar',description:'A professional introduction to CS Arisankala Manish Kumar and the principles behind his approach to professional leadership.'},
'/vision':{title:'Vision & Election | CS Arisankala Manish Kumar',description:'A factual overview of the vision of CS Arisankala Manish Kumar, expressed through ten practical commitments.'},
'/commitments':{title:'My Commitments | CS Arisankala Manish Kumar',description:'Explore ten practical commitments for professional growth, opportunity, leadership, digital readiness and a stronger professional community.'},
'/engagements':{title:'Professional Engagements | CS Arisankala Manish Kumar',description:'Sessions, seminars, professional events and speaking engagements of CS Arisankala Manish Kumar.'},
'/connect':{title:'Connect | CS Arisankala Manish Kumar',description:'Connect with CS Arisankala Manish Kumar — Company Secretary based in Kolkata.'}};
function usePath(){const[path,setPath]=useState(window.location.pathname);useEffect(()=>{const f=()=>setPath(window.location.pathname);window.addEventListener('popstate',f);return()=>window.removeEventListener('popstate',f)},[]);return path}
function navigate(path:string){window.history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo({top:0,behavior:'smooth'})}
function LinkButton({href,children,className='',onClick}:{href:string;children:React.ReactNode;className?:string;onClick?:()=>void}){return <a href={href} onClick={e=>{e.preventDefault();navigate(href);onClick?.()}} className={className}>{children}</a>}
function Header({path}:{path:string}){const[open,setOpen]=useState(false);const scrolled=useScrolled(40);const navItems=[['/','Home'],['/about','About'],['/vision','Vision'],['/commitments','Commitments'],['/engagements','Engagements'],['/connect','Connect']];return <header className={`site-header ${open?'is-open':''} ${scrolled?'is-scrolled':''}`}><div className="header-inner"><LinkButton href="/" className="wordmark" aria-label="CS Arisankala Manish Kumar home"><span>CS</span><small>ARISANKALA<br/>MANISH KUMAR</small></LinkButton><nav className="desktop-nav" aria-label="Primary navigation">{navItems.map(([href,label])=><LinkButton key={href} href={href} className={path===href?'active':''}>{label}</LinkButton>)}</nav><LinkButton href="/commitments" className="header-cta">Explore Commitments <ArrowUpRight size={15}/></LinkButton><button className="menu-button" onClick={()=>setOpen(!open)} aria-label={open?'Close menu':'Open menu'} aria-expanded={open}>{open?<X size={22}/>:<Menu size={22}/>}</button></div><nav className="mobile-nav" aria-label="Mobile navigation">{navItems.map(([href,label])=><LinkButton key={href} href={href} onClick={()=>setOpen(false)} className={path===href?'active':''}>{label}</LinkButton>)}</nav></header>}
function Eyebrow({children}:{children:React.ReactNode}){return <p className="eyebrow"><span/>{children}</p>}
function PageIntro({eyebrow,title,copy}:{eyebrow:string;title:React.ReactNode;copy?:string}){return <section className="page-intro"><div className="container intro-grid"><Eyebrow>{eyebrow}</Eyebrow><div><h1>{title}</h1>{copy&&<p className="intro-copy">{copy}</p>}</div></div></section>}
function ArrowLink({href,children}:{href:string;children:React.ReactNode}){return <LinkButton href={href} className="arrow-link">{children}<ArrowRight size={18}/></LinkButton>}
function ScrollHome(){const scrollRef=useRef<HTMLElement>(null);const progress=useScrollProgress(scrollRef);const mouse=useMouse();const reduced=useReducedMotion();const[isMobile,setIsMobile]=useState(false);useEffect(()=>{const mq=window.matchMedia('(max-width: 800px)');const u=()=>setIsMobile(mq.matches);u();mq.addEventListener('change',u);return()=>mq.removeEventListener('change',u)},[]);const layerA=Math.max(0,1-progress*1.8);const layerB=Math.min(1,Math.max(0,(progress-.12)*3))*(1-Math.max(0,(progress-.45)*2.5));const layerC=Math.min(1,Math.max(0,(progress-.32)*3))*(1-Math.max(0,(progress-.62)*2.5));const layerD=Math.min(1,Math.max(0,(progress-.5)*3))*(1-Math.max(0,(progress-.85)*4));const layerE=Math.min(1,Math.max(0,(progress-.78)*4));const heroY=reduced?0:progress*-120;const heroScale=reduced?1:1-progress*.15;const imageY=reduced?0:progress*60;const imageX=reduced?0:(mouse.x-.5)*20*(1-progress);const copyX=reduced?0:(mouse.x-.5)*-12*(1-progress);const copyY=reduced?0:(mouse.y-.5)*-8*(1-progress);const networkDensity=isMobile?.5:1;return <section ref={scrollRef} className="scroll-narrative" style={{'--p':progress} as React.CSSProperties}>
<div className="depth-layer depth-1" style={{opacity:layerA*.4}}/><div className="depth-layer depth-2" style={{opacity:layerB*.5}}/><div className="depth-layer depth-3" style={{opacity:layerC*.4}}/>
<div className="paper-sheet sheet-1" style={{transform:`translate3d(calc(-50% + ${(mouse.x-.5)*-18}px), ${progress*-55}px, 0) rotate(${progress*-2.5}deg)`,opacity:Math.max(.35,1-progress*.35)}}><span className="file-tab">Professional</span></div>
<div className="paper-sheet sheet-2" style={{transform:`translate3d(calc(-50% + ${(mouse.x-.5)*28}px), ${progress*-20}px, 0) rotate(${progress*2.2}deg)`,opacity:Math.min(.75,.25+progress*.7)}}><span className="file-tab">Vision</span></div>
<div className="paper-sheet sheet-3" style={{transform:`translate3d(calc(-50% + ${(mouse.x-.5)*-34}px), ${progress*18}px, 0) rotate(${progress*-1.6}deg)`,opacity:Math.min(.82,Math.max(0,(progress-.12)*1.3))}}><span className="file-tab">Commitments</span></div>
<div className="paper-sheet sheet-4" style={{transform:`translate3d(calc(-50% + ${(mouse.x-.5)*42}px), ${progress*52}px, 0) rotate(${progress*1.4}deg)`,opacity:Math.min(.9,Math.max(0,(progress-.3)*1.4))}}><span className="file-tab">Connection</span></div>
<div className="network-wrapper" style={{opacity:layerB}}><NetworkCanvas progress={progress} mouse={mouse} density={networkDensity}/></div>
<div className="layer layer-identity" style={{opacity:layerA,transform:`translate3d(0,${heroY}px,0) scale(${heroScale})`}}><div className="container hero-grid"><div className="hero-copy" style={{transform:`translate3d(${copyX}px,${copyY}px,0)`}}><Eyebrow>Professional profile · Upcoming candidate</Eyebrow><h1>Building a profession<br/><em>ready for what's next.</em></h1><p className="hero-description">CS Arisankala Manish Kumar is a Company Secretary and upcoming candidate focused on professional excellence, student opportunity, digital readiness and stronger institutions.</p><ArrowLink href="/vision">Explore the Vision</ArrowLink></div><div className="hero-visual" style={{transform:`translate3d(${imageX}px,${imageY}px,0)`}}><div className="hero-frame"><img src={candidateImage} alt="CS Arisankala Manish Kumar" fetchPriority="high"/></div><div className="hero-tag">CS<br/><span>Company Secretary</span></div><div className="hero-index">01 <span>/</span> 05</div></div></div><div className="hero-footer container"><span>Professional excellence · Student opportunity · Digital readiness · Stronger institutions</span><span className="scroll-hint">Scroll to explore <ArrowDown size={16}/></span></div></div>
<div className="layer layer-perspective" style={{opacity:layerB,transform:`translate3d(0,${(1-layerB)*40}px,0)`}}><div className="container perspective-grid"><Eyebrow>Layer 02 — Professional perspective</Eyebrow><h2>A network of<br/><em>knowledge and connection.</em></h2><p className="body-large">The profession is shaped by the relationships between students, members, institutions and the broader community — each connection strengthening the whole.</p></div></div>
<div className="layer layer-vision" style={{opacity:layerC,transform:`translate3d(0,${(1-layerC)*50}px,0)`}}><div className="container vision-layer-grid"><Eyebrow>Layer 03 — The vision</Eyebrow><h2>From potential<br/><em>to possibility.</em></h2><p className="vision-statement-text">A stronger, more capable and future-ready professional community — where students have opportunities, members continue to grow, and institutions remain accessible, transparent and connected to the profession.</p><ArrowLink href="/vision">View Vision & Election</ArrowLink></div></div>
<div className="layer layer-commitments" style={{opacity:layerD}}><div className="container commitments-layer"><div className="commitments-layer-heading"><Eyebrow>Layer 04 — Ten commitments</Eyebrow><h2>A clear agenda.<br/><em>Practical progress.</em></h2></div><div className="commitment-nodes">{commitments.slice(0,5).map((item,index)=><div key={item.number} className="commitment-node" style={{opacity:Math.min(1,Math.max(0,(layerD-index*.12)*2)),transform:`translate3d(0,${(1-Math.min(1,Math.max(0,(layerD-index*.12)*2)))*30}px,0)`}}><span className="node-number">{item.number}</span><span className="node-title">{item.title}</span></div>)}</div><ArrowLink href="/commitments">Explore all commitments</ArrowLink></div></div>
<div className="layer layer-connection" style={{opacity:layerE,transform:`translate3d(0,${(1-layerE)*40}px,0)`}}><div className="container connection-layer"><Eyebrow>Layer 05 — Connection</Eyebrow><h2>Explore the vision<br/><em>behind the priorities.</em></h2><div className="connection-cta"><ArrowLink href="/commitments">Explore the Commitments</ArrowLink><ArrowLink href="/connect">Connect</ArrowLink></div></div></div>
<div className="post-narrative"><section className="section introduction"><div className="container two-col"><Eyebrow>Introduction</Eyebrow><div><h2>A professional community should be equipped to <em>grow with confidence.</em></h2><p className="body-large">CS Arisankala Manish Kumar's professional vision is grounded in the belief that progress becomes meaningful when it is accessible, practical and shared.</p><p>It is a vision for a stronger, more capable and future-ready professional community — where students have opportunities, members continue to grow, and institutions remain accessible, transparent and connected to the profession.</p><ArrowLink href="/about">Discover the professional profile</ArrowLink></div></div></section><VisionBand/><CommitmentsPreview/><QRBlock/></div></section>}
function VisionBand(){return <section className="vision-band"><div className="container vision-band-inner"><div><Eyebrow>The vision</Eyebrow><h2>From potential<br/><em>to possibility.</em></h2></div><div className="vision-statement"><p>A stronger, more capable and future-ready professional community — where students have opportunities, members continue to grow, and institutions remain accessible, transparent and connected to the profession.</p><ArrowLink href="/vision">View Vision & Election</ArrowLink></div></div></section>}
function CommitmentCard({item,index}:{item:typeof commitments[number];index:number}){return <article className="commitment-card"><div className="commitment-number">{item.number}</div><div className="commitment-content"><p className="card-label">{item.label}</p><h3>{item.title}</h3><p>{item.copy}</p></div><div className="commitment-mark">{String(index+1).padStart(2,'0')}</div></article>}
function CommitmentsPreview(){return <section className="section commitments-preview"><div className="container commitment-layout"><div className="sticky-heading"><Eyebrow>Ten commitments</Eyebrow><h2>A clear agenda.<br/><em>Practical progress.</em></h2><p>Ten priorities for a profession that is more capable, connected and ready for the future.</p><ArrowLink href="/commitments">Explore all commitments</ArrowLink></div><div className="commitment-list">{commitments.slice(0,5).map((item,index)=><CommitmentCard key={item.number} item={item} index={index}/>)}<div className="more-commitments"><span>05 more priorities</span><ArrowLink href="/commitments">See the complete vision</ArrowLink></div></div></div></section>}
function QRBlock({heading='Explore the Commitments',subtext='Scan to read the complete vision and commitments.'}:{heading?:string;subtext?:string}){const[src,setSrc]=useState('');useEffect(()=>{QRCode.toDataURL(`${siteUrl}/commitments`,{width:280,margin:1,color:{dark:'#102a43',light:'#ffffff'}}).then(setSrc)},[]);return <section className="qr-section"><div className="container qr-layout"><div><Eyebrow>Take the vision with you</Eyebrow><h2>{heading.split(' ').slice(0,-1).join(' ')}<br/><em>{heading.split(' ').slice(-1)[0]}.</em></h2><p>{subtext}</p></div><div className="qr-card">{src?<img src={src} alt="QR code linking to the commitments page"/>:<div className="qr-placeholder" aria-hidden="true"/>}<div><strong>csmanishkumar.com/commitments</strong><span>Scan to open</span></div></div></div></section>}
function Home(){return <><ScrollHome/><Footer/></>}
function About(){return <><PageIntro eyebrow="About the candidate" title={<>Professional clarity.<br/><em>Purposeful leadership.</em></>} copy="A professional introduction grounded in the information shared for this profile."/><section className="section about-content"><div className="container about-grid"><div className="about-image"><img src={candidateImage} alt="CS Arisankala Manish Kumar" loading="lazy"/></div><div className="about-text"><Eyebrow>Professional introduction</Eyebrow><h2>Focused on the work<br/>that moves people <em>forward.</em></h2><p className="body-large">CS Arisankala Manish Kumar is a Company Secretary and upcoming candidate for the relevant CS election.</p><p>This profile presents a stated vision for professional excellence, student opportunity, digital readiness and stronger institutions. It is intentionally focused on the commitments and the community they are designed to serve.</p><div className="principles"><div><span>01</span><strong>Professional excellence</strong></div><div><span>02</span><strong>Student opportunity</strong></div><div><span>03</span><strong>Digital readiness</strong></div><div><span>04</span><strong>Stronger institutions</strong></div></div></div></div></section><section className="quote-section"><div className="container"><p>“A future-ready professional community is built through opportunity, capability and connection.”</p><span>— The professional vision</span></div></section><Footer/></>}
function Vision(){return <><PageIntro eyebrow="Vision & election" title={<>A future-ready profession<br/><em>starts with action.</em></>} copy="The stated vision is expressed through ten practical commitments for students, members and institutions."/><section className="section vision-intro"><div className="container vision-intro-grid"><Eyebrow>The central idea</Eyebrow><div><h2>Stronger capability.<br/><em>Shared opportunity.</em></h2><p className="body-large">A stronger, more capable and future-ready professional community — where students have opportunities, members continue to grow, and institutions remain accessible, transparent and connected to the profession.</p><p>The ten commitments below provide the structure for that vision. They cover professional development, student readiness, employment, leadership, digital capability, collaboration, engagement, welfare, research and institutional responsiveness.</p></div></div></section><section className="section full-commitments"><div className="container"><div className="section-heading"><Eyebrow>Ten priorities</Eyebrow><h2>The commitments<br/><em>in full.</em></h2></div><div className="full-list">{commitments.map((item,index)=><CommitmentCard key={item.number} item={item} index={index}/>)}</div></div></section><Footer/></>}
function CommitmentsPage(){return <><PageIntro eyebrow="Ten priorities" title={<>My<br/><em>commitments.</em></>} copy="A practical vision for professional growth, opportunity, leadership, digital readiness and a stronger professional community."/><section className="commitments-page-list"><div className="container"><div className="commitments-page-note"><span>01—10</span><p>Each commitment is a step toward a profession that is more capable, connected and ready for what's next.</p></div>{commitments.map((item,index)=><CommitmentCard key={item.number} item={item} index={index}/>)}</div></section><section className="end-cta"><div className="container"><Eyebrow>Continue exploring</Eyebrow><h2>See the vision<br/><em>behind the priorities.</em></h2><div className="end-links"><ArrowLink href="/vision">Explore the Vision</ArrowLink><ArrowLink href="/connect">Connect</ArrowLink></div></div></section><Footer/></>}
function Engagements(){const items=[{title:'Professional Sessions',text:'Sessions and knowledge-sharing interactions with students, members and professional communities.',label:'Sessions'},{title:'Professional Seminars',text:'Participation in professional seminars and forums focused on learning, practice and emerging developments.',label:'Seminars'},{title:'Professional Events',text:'Engagement with professional events and institutional interactions across the community.',label:'Events'},{title:'Speaking & Spokesperson Engagements',text:'Public-facing professional conversations, speaking opportunities and representation where applicable.',label:'Speaking'}];return <><PageIntro eyebrow="Professional engagements" title={<>Sessions. Seminars.<br/><em>Professional exchange.</em></>} copy="A visual record of professional sessions, seminars, events and speaking engagements."/><section className="section engagements-page"><div className="container"><div className="engagement-intro"><Eyebrow>Engagement in practice</Eyebrow><p className="body-large">Professional growth is strengthened through participation, knowledge-sharing and meaningful connection.</p></div><div className="engagement-grid">{items.map((item,i)=><article className="engagement-card" key={item.label}><div className={`engagement-media media-${i+1}`}><span>{item.label}</span></div><div className="engagement-copy"><small>{String(i+1).padStart(2,'0')}</small><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div><p className="engagement-note">Photographs and event-specific details can be added to this gallery as verified material is supplied.</p></div></section><Footer/></>}
function Connect(){return <><PageIntro eyebrow="Connect" title={<>A professional vision<br/><em>worth discussing.</em></>} copy="Connect with CS Arisankala Manish Kumar — Company Secretary based in Kolkata."/><section className="section connect-content"><div className="container connect-grid"><div><Eyebrow>Start with the vision</Eyebrow><h2>Good institutions are built through <em>conversation.</em></h2><p className="body-large">The commitments are an invitation to engage with a practical vision for professional growth, opportunity, leadership and a future-ready community.</p><ArrowLink href="/commitments">Read the commitments</ArrowLink></div><div className="connect-panel"><div className="contact-row contact-name"><span>Profile</span><strong>CS Arisankala Manish Kumar</strong></div><div className="contact-row contact-location"><span>Location</span><strong><MapPin size={14}/> {contact.location}</strong></div><a href={`mailto:${contact.email}`} className="contact-row contact-email"><span>Email</span><strong><Mail size={14}/> {contact.email}</strong></a><a href={`tel:${contact.phoneIntl}`} className="contact-row contact-phone"><span>Phone</span><strong><Phone size={14}/> {contact.phone}</strong></a></div></div></section><QRBlock/><Footer/></>}
function Footer(){return <footer className="site-footer"><div className="container footer-top"><LinkButton href="/" className="wordmark"><span>CS</span><small>ARISANKALA<br/>MANISH KUMAR</small></LinkButton><p>Professional Excellence.<br/>Student Opportunity.<br/>Digital Readiness.<br/>Stronger Institutions.</p><div className="footer-links"><LinkButton href="/vision">Vision & Election</LinkButton><LinkButton href="/commitments">My Commitments</LinkButton><LinkButton href="/engagements">Engagements</LinkButton><LinkButton href="/connect">Connect</LinkButton></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} CS Arisankala Manish Kumar</span><span>Company Secretary · Kolkata</span></div></footer>}
function App(){const path=usePath();const page=useMemo(()=>pages[path]||pages['/'],[path]);useEffect(()=>{document.title=page.title;const d=document.querySelector('meta[name="description"]');if(d)d.setAttribute('content',page.description);const c=document.querySelector('link[rel="canonical"]');if(c)c.setAttribute('href',`${siteUrl}${path==='/'?'':path}`);},[page,path]);const content=path==='/about'?<About/>:path==='/vision'?<Vision/>:path==='/commitments'?<CommitmentsPage/>:path==='/engagements'?<Engagements/>:path==='/connect'?<Connect/>:<Home/>;return <><Header path={path}/><main>{content}</main></>}
export default App;
