import { useState } from 'react';
import { ArrowUpRight, X } from 'lucide-react';

const galleryItems = [
  { image:'/images/award-01-tongue-twister-judge.png', year:'2025', title:'Tongue Twister Competition', caption:'Hon. Judge · Hooghly Chapter of EIRC of ICSI · Mega Student Carnival' },
  { image:'/images/award-02-pcs-day.png', year:'2025', title:'PCS Day Recognition', caption:'EIRC of ICSI · Professional recognition' },
  { image:'/images/award-03-mega-student-conference.png', year:'2023', title:"Mega Student's Conference", caption:'ICSI · Presented to CS Arisankala Manish Kumar' },
  { image:'/images/award-04-hooghly-chapter.png', year:'Professional', title:'Hooghly Chapter Recognition', caption:'ICSI · Hooghly Chapter' },
  { image:'/images/award-05-posh-session.png', year:'2026', title:'Professional Knowledge Session', caption:'Madhya Kolkata Study Circle for Members of ICSI-EIRC · POSH' },
  { image:'/images/award-06-adapting-mca-v3.png', year:'2025', title:'Adapting to MCA V3', caption:'ICMAI Howrah Chapter · ROC transition & compliance' },
  { image:'/images/award-07-gst-input-tax-credit.png', year:'2026', title:'Input Tax Credit under GST', caption:'ICMAI Howrah Chapter · Knowledge session' },
  { image:'/images/award-08-gst-rate-cuts.png', year:'2025', title:'Impact of GST Rate Cuts', caption:'ICMAI Howrah Chapter · GST Council insights' },
  { image:'/images/award-09-mca-v3-solutions.png', year:'Professional', title:'MCA-V3 Portal: Common Errors & Solutions', caption:'ICMAI Howrah Chapter' },
  { image:'/images/award-10-hooghly-chapter-gratitude.png', year:'2024', title:'Knowledge-Sharing Recognition', caption:'Hooghly Chapter of ICSI · Full Day Seminar' },
  { image:'/images/award-11-bhawanipur-education-appreciation.png', year:'Professional', title:'Appreciation for Support in Education', caption:'The Bhawanipur Education Society College' },
  { image:'/images/award-12-moot-court-competition.png', year:'2026', title:'24th All India Moot Court Competition', caption:'ICSI-EIRC · CCGR&T Kolkata Campus' },
  { image:'/images/award-13-regional-conference.png', year:'2017', title:'9th Regional Conference of Student Company Secretaries', caption:'ICSI-EIRC jointly with Hooghly Chapter' },
  { image:'/images/award-14-3rd-best-participant.png', year:'2016', title:'3rd Best Participant — 112th MSOP', caption:'ICSI-EIRC · Management Skills Orientation Programme · Kolkata' },
];

export default function Gallery(){
 const [active,setActive]=useState<number|null>(null);
 return <div className="gallery-page">
  <style>{`@keyframes recognitionMarquee{from{transform:translateX(0)}to{transform:translateX(-50%)}}.recognition-marquee{background:#102a43;color:#fff;padding:26px 0 30px;overflow:hidden;border-top:1px solid rgba(255,255,255,.08);border-bottom:1px solid rgba(255,255,255,.08)}.marquee-label{width:min(1180px,calc(100% - 48px));margin:0 auto 17px;display:flex;justify-content:space-between;align-items:center;gap:20px}.marquee-label span{font-size:10px;letter-spacing:2px;text-transform:uppercase;color:#d7a06c;font-weight:750}.marquee-label small{font-size:10px;letter-spacing:.8px;color:rgba(255,255,255,.48)}.marquee-window{overflow:hidden;width:100%}.marquee-track{display:flex;width:max-content;gap:14px;animation:recognitionMarquee 85s linear infinite}.marquee-track:hover{animation-play-state:paused}.marquee-card{width:245px;flex:0 0 245px;display:grid;grid-template-columns:78px 1fr;align-items:center;gap:12px;padding:9px;background:rgba(255,255,255,.055);border:1px solid rgba(255,255,255,.12);color:#fff;text-align:left;cursor:pointer}.marquee-card:hover{background:rgba(255,255,255,.1)}.marquee-image{height:78px;background:transparent;display:flex;align-items:center;justify-content:center;overflow:hidden}.marquee-image img{width:100%;height:100%;object-fit:contain;mix-blend-mode:normal}.marquee-card small{display:block;color:#d7a06c;font-size:9px;letter-spacing:1.2px;text-transform:uppercase;margin-bottom:5px}.marquee-card strong{display:block;font-size:12px;line-height:1.25;font-weight:650}.gallery-media{background:transparent!important;padding:24px!important;height:430px!important;align-items:center!important;justify-content:center!important}.gallery-media img{width:100%!important;height:100%!important;object-fit:contain!important;mix-blend-mode:normal!important;filter:none!important}.gallery-card{background:transparent!important}.gallery-media::before{content:'';position:absolute;inset:0;background:transparent;pointer-events:none;z-index:-1}.gallery-lightbox img{background:transparent!important}@media(max-width:700px){.marquee-label{width:calc(100% - 32px);display:block}.marquee-label small{display:block;margin-top:7px}.marquee-track{animation-duration:65s}.marquee-card{width:210px;flex-basis:210px;grid-template-columns:68px 1fr}.marquee-image{height:68px}.gallery-media{height:380px!important;padding:20px!important}}`}</style>
  <header className="gallery-header"><a href="/" className="gallery-brand"><b>CS</b><span>ARISANKALA<br/>MANISH KUMAR</span></a><nav><a href="/">Home</a><a href="/about">About</a><a href="/vision">Vision</a><a href="/commitments">Commitments</a><a className="active" href="/gallery">Galleries</a><a href="/connect">Connect</a></nav><a className="gallery-cta" href="/commitments">Explore Commitments <ArrowUpRight size={15}/></a></header>
  <main>
   <section className="gallery-hero"><div className="gallery-container"><p className="gallery-eyebrow">Professional life · Moments · Events</p><h1>A visual record of<br/><em>the journey.</em></h1><p>A growing collection of photographs from professional events, knowledge-sharing sessions, institutional engagements and moments of recognition.</p></div></section>
   <section className="recognition-marquee" aria-label="Selected recognitions"><div className="marquee-label"><span>Selected recognitions</span><small>Recognition archive</small></div><div className="marquee-window"><div className="marquee-track">{galleryItems.map((item,i)=><button className="marquee-card" key={`${item.image}-${i}`} onClick={()=>setActive(i)} aria-label={`View ${item.title}`}><div className="marquee-image"><img src={item.image} alt=""/></div><div><small>{item.year}</small><strong>{item.title}</strong></div></button>)}{galleryItems.map((item,i)=><button className="marquee-card" key={`repeat-${item.image}-${i}`} onClick={()=>setActive(i)} aria-label={`View ${item.title}`}><div className="marquee-image"><img src={item.image} alt=""/></div><div><small>{item.year}</small><strong>{item.title}</strong></div></button>)}</div></div></section>
   <section className="gallery-moments"><div className="gallery-container"><div className="gallery-heading"><div><span>01 — MOMENTS & EVENTS</span><h2>Moments from<br/><em>the profession.</em></h2></div><p>Photographs are kept as individual moments rather than compressed into a single collage, so the people, setting and recognition remain visually distinct.</p></div><div className="gallery-grid">{galleryItems.map((item,i)=><article className="gallery-card" key={item.image} onClick={()=>setActive(i)}><div className="gallery-media"><img src={item.image} alt={item.title} loading="lazy"/><span>Open <ArrowUpRight size={14}/></span></div><div className="gallery-meta"><small>{item.year}</small><small>{String(i+1).padStart(2,'0')}</small></div><h3>{item.title}</h3><p>{item.caption}</p></article>)}</div></div></section>
   <section className="gallery-awards"><div className="gallery-container"><div className="gallery-awards-heading"><span>02 — INDIVIDUAL RECOGNITIONS</span><h2>The recognitions<br/><em>behind the photographs.</em></h2><p>Individual awards remain available here as a clean archive, while the main gallery keeps the focus on the wider professional journey.</p></div><div className="recognition-list">{galleryItems.map((item,i)=><button key={item.image} onClick={()=>setActive(i)}><span>{String(i+1).padStart(2,'0')}</span><strong>{item.title}</strong><small>{item.year}</small><ArrowUpRight size={16}/></button>)}</div></div></section>
  </main>
  <footer className="gallery-footer"><span>© {new Date().getFullYear()} CS Arisankala Manish Kumar</span><span>Company Secretary · Kolkata</span></footer>
  {active!==null&&<div className="gallery-lightbox" role="dialog" aria-modal="true" onClick={()=>setActive(null)}><button aria-label="Close" onClick={()=>setActive(null)}><X size={22}/></button><div onClick={e=>e.stopPropagation()}><img src={galleryItems[active].image} alt={galleryItems[active].title}/><h3>{galleryItems[active].title}</h3><p>{galleryItems[active].caption}</p></div></div>}
 </div>
}
